"""meta-processo

Revision ID: 07f7bc37e09f
Revises: 6302b6f9371e
Create Date: 2024-09-30 19:41:14.834003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f7bc37e09f'
down_revision: Union[str, None] = '6302b6f9371e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metaProcesso',
    sa.Column('NumeroProcesso', sa.String(length=255), nullable=False),
    sa.Column('NumeroProcessoConsulta', sa.String(length=255), nullable=False),
    sa.Column('Tipo', sa.String(length=255), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_metaProcesso_NumeroProcesso'), 'metaProcesso', ['NumeroProcesso'], unique=True)
    op.create_index(op.f('ix_metaProcesso_NumeroProcessoConsulta'), 'metaProcesso', ['NumeroProcessoConsulta'], unique=False)
    op.create_index(op.f('ix_metaProcesso_updated_at'), 'metaProcesso', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metaProcesso_updated_at'), table_name='metaProcesso')
    op.drop_index(op.f('ix_metaProcesso_NumeroProcessoConsulta'), table_name='metaProcesso')
    op.drop_index(op.f('ix_metaProcesso_NumeroProcesso'), table_name='metaProcesso')
    op.drop_table('metaProcesso')
    # ### end Alembic commands ###
