"""add polos

Revision ID: 1d917a766c3e
Revises: 
Create Date: 2024-07-19 00:34:13.671525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d917a766c3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processo',
    sa.Column('NumeroProcesso', sa.String(length=255), nullable=True),
    sa.Column('Classe', sa.String(length=255), nullable=True),
    sa.Column('NomePoloPassivo', sa.String(length=255), nullable=True),
    sa.Column('NomePoloAtivo', sa.String(length=255), nullable=True),
    sa.Column('Assunto', sa.String(length=255), nullable=True),
    sa.Column('Valor', sa.String(length=255), nullable=True),
    sa.Column('Serventia', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_processo_NumeroProcesso'), 'processo', ['NumeroProcesso'], unique=True)
    op.create_index(op.f('ix_processo_updated_at'), 'processo', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processo_updated_at'), table_name='processo')
    op.drop_index(op.f('ix_processo_NumeroProcesso'), table_name='processo')
    op.drop_table('processo')
    # ### end Alembic commands ###
