"""AlteracaoTamanhoEvalorNum

Revision ID: 41aefb915ec8
Revises: 4cca3f6a47af
Create Date: 2024-11-07 23:30:42.515251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41aefb915ec8'
down_revision: Union[str, None] = '4cca3f6a47af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
