"""fix-num-process

Revision ID: 5b72edeba560
Revises: 8d21bbeff062
Create Date: 2024-12-14 19:24:58.527219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b72edeba560'
down_revision: Union[str, None] = '8d21bbeff062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metaProcesso_NumeroProcessoConsulta', table_name='metaProcesso')
    op.create_index(op.f('ix_metaProcesso_NumeroProcessoConsulta'), 'metaProcesso', ['NumeroProcessoConsulta'], unique=True)
    op.drop_index('ix_processo_NumeroProcessoConsulta', table_name='processo')
    op.create_index(op.f('ix_processo_NumeroProcessoConsulta'), 'processo', ['NumeroProcessoConsulta'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processo_NumeroProcessoConsulta'), table_name='processo')
    op.create_index('ix_processo_NumeroProcessoConsulta', 'processo', ['NumeroProcessoConsulta'], unique=False)
    op.drop_index(op.f('ix_metaProcesso_NumeroProcessoConsulta'), table_name='metaProcesso')
    op.create_index('ix_metaProcesso_NumeroProcessoConsulta', 'metaProcesso', ['NumeroProcessoConsulta'], unique=False)
    # ### end Alembic commands ###
