"""add serventia2

Revision ID: 6302b6f9371e
Revises: d041f269c4d7
Create Date: 2024-07-19 15:00:36.836053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6302b6f9371e'
down_revision: Union[str, None] = 'd041f269c4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processo', sa.Column('Serventia2', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processo', 'Serventia2')
    # ### end Alembic commands ###
