"""add-data-pub

Revision ID: 9b994ebd10b3
Revises: 07f7bc37e09f
Create Date: 2024-10-13 10:47:51.225925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b994ebd10b3'
down_revision: Union[str, None] = '07f7bc37e09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metaProcesso', sa.Column('DataPublicacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metaProcesso', 'DataPublicacao')
    # ### end Alembic commands ###
