"""add_relacionamento

Revision ID: b9011c0354ef
Revises: 9b994ebd10b3
Create Date: 2024-10-16 23:41:51.906144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9011c0354ef'
down_revision: Union[str, None] = '9b994ebd10b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processo', sa.Column('meta_processo_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'processo', 'metaProcesso', ['meta_processo_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processo', type_='foreignkey')
    op.drop_column('processo', 'meta_processo_id')
    # ### end Alembic commands ###
