"""add numero consulta

Revision ID: d041f269c4d7
Revises: 1d917a766c3e
Create Date: 2024-07-19 13:55:10.341763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd041f269c4d7'
down_revision: Union[str, None] = '1d917a766c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processo', sa.Column('NumeroProcessoConsulta', sa.String(length=255), nullable=True))
    op.add_column('processo', sa.Column('CpfCNPJPoloPassivo', sa.String(length=255), nullable=True))
    op.add_column('processo', sa.Column('CpfCNPJNomePoloAtivo', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_processo_NumeroProcessoConsulta'), 'processo', ['NumeroProcessoConsulta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processo_NumeroProcessoConsulta'), table_name='processo')
    op.drop_column('processo', 'CpfCNPJNomePoloAtivo')
    op.drop_column('processo', 'CpfCNPJPoloPassivo')
    op.drop_column('processo', 'NumeroProcessoConsulta')
    # ### end Alembic commands ###
